### ISSUE TITLE
How to estimate kernels of real-world images

### ISSUE THREAD

**Issue by m-tassano** [alsgur0720/multiregression#2]
Hi,

I tried running the code to estimate the kernel of real images (without generating a LR-HR pair), but it crashes due to the following error when the `parameter_extractor()` is called in line 66 in `multiregression_arch.py` : 

``RuntimeError: Calculated padded input size per channel: (3 x 3). Kernel size: (5 x 5). Kernel size can't be greater than actual input size``

To test the code on real images, I modified/added the following params in `options/test/test_stage1.yml` :

>datasets:
>  test_1:
>    name: real_world
>    mode: LQ
>    dataroot_LQ: dir-with-real-image
>    kernel_size: 21

By the way, I succeeded in running the code for the "GT" case, but I haven't been able to make it run for the "LQ" one.  Is the case of estimating kernels in a real image supported? If so, is there something am I missing? I'd appreciate if you could help me with getting it running.

Thanks

**Comment by alsgur0720** [comment]
We are sorry, but we do not support kernel estimation on real images.
